@echo off
REM ---------------------------------------------------------------------
REM setup-repo.bat
REM
REM Windows batch equivalent of setup-repo.sh for Module 13.
REM Demonstrates: init -> add/commit -> branch -> edit/commit ->
REM               switch back -> merge -> log
REM
REM Usage:
REM   setup-repo.bat [target-directory]
REM
REM If no target directory is given, "dn5-git-demo" is used.
REM ---------------------------------------------------------------------

setlocal enabledelayedexpansion

set "TARGET_DIR=%~1"
if "%TARGET_DIR%"=="" set "TARGET_DIR=dn5-git-demo"

echo ^>^> Creating and entering project directory: %TARGET_DIR%
if not exist "%TARGET_DIR%" mkdir "%TARGET_DIR%"
cd "%TARGET_DIR%"

echo ^>^> Initializing git repository
git init -b main 2>nul
if errorlevel 1 (
    git init
    git checkout -b main
)

echo ^>^> Configuring local commit identity (only if not already set)
git config user.name >nul 2>nul
if errorlevel 1 git config user.name "DN5 Trainee"
git config user.email >nul 2>nul
if errorlevel 1 git config user.email "trainee@example.com"

echo ^>^> Creating initial README.md
(
  echo # DN5 Git Demo
  echo.
  echo This repository was generated by scripts\setup-repo.bat to demonstrate the
  echo init -^> commit -^> branch -^> merge workflow from Module 13.
) > README.md

echo ^>^> Staging and committing initial file
git add README.md
git commit -m "Initial commit: add README"

echo ^>^> Creating and switching to feature/sample branch
git checkout -b feature/sample

echo ^>^> Making a change on the feature branch
(
  echo.
  echo ## Feature Update
  echo.
  echo This line was added on the feature/sample branch.
) >> README.md

git add README.md
git commit -m "feature/sample: document the feature branch change"

echo ^>^> Switching back to main
git checkout main

echo ^>^> Merging feature/sample into main
git merge feature/sample -m "Merge feature/sample into main"

echo ^>^> Final history graph
git log --oneline --graph --all

echo ^>^> Done. Repository created at: %cd%

endlocal
