#!/usr/bin/env bash
#
# setup-repo.sh
#
# Demonstrates the core Git loop for Module 13:
#   init -> add/commit -> branch -> edit/commit -> switch back -> merge -> log
#
# Usage:
#   chmod +x setup-repo.sh
#   ./setup-repo.sh [target-directory]
#
# If no target directory is given, a new folder "dn5-git-demo" is created
# in the current working directory.

set -euo pipefail

TARGET_DIR="${1:-dn5-git-demo}"

echo ">> Creating and entering project directory: ${TARGET_DIR}"
mkdir -p "${TARGET_DIR}"
cd "${TARGET_DIR}"

echo ">> Initializing git repository"
git init -b main 2>/dev/null || { git init; git checkout -b main; }

echo ">> Configuring local commit identity (only if not already set)"
git config user.name  >/dev/null 2>&1 || git config user.name  "DN5 Trainee"
git config user.email >/dev/null 2>&1 || git config user.email "trainee@example.com"

echo ">> Creating initial README.md"
cat > README.md <<'EOF'
# DN5 Git Demo

This repository was generated by scripts/setup-repo.sh to demonstrate the
init -> commit -> branch -> merge workflow from Module 13.
EOF

echo ">> Staging and committing initial file"
git add README.md
git commit -m "Initial commit: add README"

echo ">> Creating and switching to feature/sample branch"
git checkout -b feature/sample

echo ">> Making a change on the feature branch"
cat >> README.md <<'EOF'

## Feature Update

This line was added on the feature/sample branch.
EOF

git add README.md
git commit -m "feature/sample: document the feature branch change"

echo ">> Switching back to main"
git checkout main

echo ">> Merging feature/sample into main"
git merge feature/sample -m "Merge feature/sample into main"

echo ">> Final history graph"
git log --oneline --graph --all

echo ">> Done. Repository created at: $(pwd)"
